name: AutoFlowHub CI/CD

on:
  push:
    branches:
      - 'features/**'
      - 'bugfix/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and test
        run: |
          go build -v ./...
          go test -v ./...
        

      - name: Get version and create a new release branch
        if: ${{ success() }}
        run: |
          chmod +x ./scripts/version.sh
          export NEW_VERSION=$(./scripts/version.sh)
          echo "Current version is $NEW_VERSION"
          export NEW_BRANCH="release/${NEW_VERSION}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b $NEW_BRANCH
          git commit --allow-empty -m "Bump version to ${NEW_VERSION}"
          git remote set-url origin https://${{ secrets.GH_ACTIONS_TOKEN }}@github.com/MrLutik/autoflowhub.git
          git push --set-upstream https://github.com/MrLutik/autoflowhub.git $NEW_BRANCH --force --quiet




  create-pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge release branch"
          branch: "autorelease/${{ github.run_number }}"
          title: "Automerge: Release branch"
          body: "Automatically created PR to merge the release branch."
          base: "master"
          labels: "autorelease"
          auto-merge-method: "merge"
          auto-merge: true

